# -*- coding: utf-8 -*-
"""Edu Tutor AI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BJP4ZwZYr-rC8zA_rkPOQaPaGtchyGpa
"""

import random

# Question bank with levels
questions = {
    "easy": [
        ("2 + 2 = ?", "4"),
        ("5 - 3 = ?", "2"),
    ],
    "medium": [
        ("12 / 3 = ?", "4"),
        ("15 + 6 = ?", "21"),
    ],
    "hard": [
        ("Solve: 2x + 3 = 7 → x = ?", "2"),
        ("Square root of 144?", "12"),
    ]
}

# Track student progress
student_profile = {"score": 0, "level": "easy"}

def ask_question(level):
    q, ans = random.choice(questions[level])
    user_ans = input(q + " ")
    if user_ans == ans:
        print("✅ Correct!")
        student_profile["score"] += 1
    else:
        print(f"❌ Wrong. Correct answer: {ans}")

def adjust_level():
    if student_profile["score"] > 3:
        student_profile["level"] = "medium"
    if student_profile["score"] > 6:
        student_profile["level"] = "hard"

# --- Edu Tutor AI in action ---
print("🤖 Welcome to Edu Tutor AI – Your Personalized Learning Assistant!")

for i in range(8):  # 8 practice questions
    lvl = student_profile["level"]
    ask_question(lvl)
    adjust_level()

print("\n📊 Final Report")
print("Score:", student_profile["score"])
print("Learning Level Reached:", student_profile["level"])